# Generated by Django 5.0.2 on 2025-04-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='professor_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_auxiliar', to='core.professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='professor_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_titular', to='core.professor'),
        ),
    ]
