# Generated by Django 5.0.2 on 2025-04-15 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aluno_professor_auxiliar_aluno_professor_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.CreateModel(
            name='PessoaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('documento', models.CharField(help_text='RG ou outro documento de identificação', max_length=20)),
                ('parentesco', models.CharField(help_text='Ex: Tio, Avó, Babá, etc', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autorizados/')),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_autorizadas', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Pessoa Autorizada',
                'verbose_name_plural': 'Pessoas Autorizadas',
                'ordering': ['aluno', 'nome'],
            },
        ),
    ]
