# Generated by Django 5.0.2 on 2025-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aluno_cpf_aluno_rg_pessoaautorizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoaautorizada',
            name='documento',
        ),
        migrations.AddField(
            model_name='pessoaautorizada',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='pessoaautorizada',
            name='foto_documento',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/', verbose_name='Foto do Documento'),
        ),
        migrations.AddField(
            model_name='pessoaautorizada',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='pessoaautorizada',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autorizados/', verbose_name='Foto da Pessoa'),
        ),
    ]
