# Generated by Django 5.0.2 on 2025-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aluno_options_aluno_ativo_aluno_cep_and_more'),
    ]

    operations = [
    ]
