# Generated by Django 5.0.2 on 2025-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aluno_bairro_aluno_cep_aluno_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado_civil_mae',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado_civil_pai',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil do Pai'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissao_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissao_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão do Pai'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone_mae',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone_pai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do Pai'),
        ),
    ]
